################ English language ##################
[en]
languageName = "English"
languageCode = "eng"
contentDir = "content/en"
weight = 1

################ Norwegian language ##################
[no]
languageName = "Norsk bokmål"
languageCode = "nob"
contentDir = "content/no"
weight = 2

################ Northern Sámi language ##################
[sme]
languageName = "Davvisámegiella"
languageCode = "sme"
contentDir = "content/sme"
weight = 3