############# English navigation ##############

# main menu
[[main]]
name = "Ruoktot"
url = "/"
weight = 1

[[main]]
name = "Birra"
url = "/about"
weight = 2

[[main]]
name = "Oassálas"
url = "/partners"
weight = 3

[[main]]
name = "Ođđasat"
url = "/blog"
weight = 4

[[main]]
name = "Oktavuohta"
url = "/contact"
weight = 5


# footer menu
[[footer]]
name = "Birra"
url = "/about"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 2
