############# Norwegian navigation ##############

# main menu
[[main]]
name = "Forside"
url = "/"
weight = 1

[[main]]
name = "Om oss"
url = "/om"
weight = 2

[[main]]
name = "Partnere"
url = "/partnere"
weight = 3

[[main]]
name = "Nyheter"
url = "/blog"
weight = 4

[[main]]
name = "Kontakt"
weight = 5
url = "/contact"


# footer menu
[[footer]]
name = "Om WebData"
url = "/about"
weight = 1

[[footer]]
name = "Personvern"
url = "/privacy-policy"
weight = 2
