############# English navigation ##############

# main menu
[[main]]
name = "Ruoktot"
url = "/"
weight = 1

[[main]]
name = "Birra"
url = "/birra"
weight = 2

[[main]]
name = "Oassálas"
url = "/oassalas"
weight = 3

#[[main]]
#name = "Ođđasat"
#url = "/oddasat"
#weight = 4

[[main]]
name = "Oktavuohta"
url = "/contact"
weight = 5


# footer menu
[[footer]]
name = "Birra"
url = "/birra"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 2
